<?php

namespace app\index\controller;

use app\common\WechatOline;
use app\index\model\User;
//use think\Cache;
use think\Controller;
use think\Db;
use think\Exception;
use think\facade\Cache;
use think\facade\Log;
use think\facade\Session;
use think\Request;

class Base extends Controller
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        try {
            if (!Cache::has('AccessToken')) {
                $this->accessToken();
            }
        } catch (\Exception $e) {
            Log::error($e);
        }

        if (!Session::has('user')) {
//            $login = (new Login())->login();
            $user = User::field('id,nickname,wechatid,agency_id,avatar,status,openid')->with(['agency'=>function($query){
                $query->field('id,title');
            }])->where('id', 24)->find();
            Session::set('user', $user);
        } else {
            $openid = Session::get('user');
            $key_openid = array_key_exists('openid',$openid);
            if($key_openid){
                $openid = $openid['openid'];
                $user = Db::name('user')->where('openid', $openid);
                if (!$user) {
                    $user = User::field('id,nickname,wechatid,agency_id,avatar,status,openid')->with(['agency'=>function($query){
                    $query->field('id,title');
                }])->where('id', 24)->find();
                Session::set('user', $user);
                }
            }else{
                $user = User::field('id,nickname,wechatid,agency_id,avatar,status,openid')->with(['agency'=>function($query){
                    $query->field('id,title');
                }])->where('id', 24)->find();
                Session::set('user', $user);
            }
        }


//session('user',null);
//        if (!Session::has('user')) {
//            Log::error('se_false');
//            $login = (new Login())->login();
//        } else {
//            $openid = Session::get('user');
//            $key_openid = array_key_exists('openid',$openid);
//            if($key_openid){
//                $openid = $openid['openid'];
//                $user = Db::name('user')->where('openid', $openid)->count('id');
//                if (!$user) {
//                    Log::error('user_false');
//                    $login = (new Login())->login();
//                }
//            }else{
//                Log::error('key_false');
//                $login = (new Login())->login();
//            }
//        }
        $this->assign('user', \session('user'));
    }

    public function accessToken()
    {
        static $num = 1;
            $url = config('wechat.token_url');
            $app = [
                'grant_type' => 'client_credential',
                'appid' => config('wechat.app_id'),
                'secret' => config('wechat.app_secret'),
            ];
            $url = $url . '?' . http_build_query($app);

            $curl = curl_init();
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($curl, CURLOPT_URL, $url);

            $json = curl_exec($curl);
            curl_close($curl);
            $json = json_decode($json, true);
            if (array_key_exists('errcode', $json)) {
                throw new Exception('获取token失败:' . $json);
            }
            Log::error('1-access');
            Cache::set('AccessToken', $json['access_token'],7000);
    }

    /**
     * 获取js-sdk签名所需ticket
     */
    public function jsApiTicket(){
        if(!Cache::has('AccessToken')){
            $this->accessToken();
        }
        $access_token = Cache::get('AccessToken');
        $url = 'https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token='.$access_token.'&type=jsapi';
        $js_api = (new WechatOline())->http_url($url);
        $js_api = json_decode($js_api,true);
        if($js_api['errcode']==0){
            Cache::set('jsApiTicket',$js_api['ticket'],7000);
        }
    }

}
